# Generated by Django 2.2.12 on 2021-03-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Group', verbose_name='Group')),
            ],
        ),
    ]
